### ISSUE TITLE
Installing through NPM

### ISSUE THREAD

**Issue by tomverran** [ensime/ensime-node#19]
Hello,

It looks like the NPM version of this package consists of the typescript sources rather than compiled JS / typings files. The library does attempt to build itself with a postInstall task but that requires a global gulp / typings installation and all the devDependencies which are not pulled in.

I'm happy to have a go at a build process that only publishes the contents of release/ but thought I should check in here first to find out if I am misunderstanding something around how NPM handles self-compiling packages.

**Comment by hedefalk** [comment]
Hi and whoops! 

Awesome, I'd love to get some help with that! Got something up in a rush, but it might be erroneous as you state. Could you base off my personal branch that is a couple of commits ahead of this one:

https://github.com/hedefalk/ensime-node/commit/396dd105d49f1cba6b23bd9f694315a4d9679cf8

I'm in a run right now so don't have the time to look at merging it right now, but if it looks ok, base it of that, otherwise go on master here.

Thanks!

**Comment by hedefalk** [comment]
@tomverran Did you proceed with this?

Anyways, the main seems to be set to release/lib/index.js as of June:

https://github.com/ensime/ensime-node/commit/d0ea10fff6155d6f9d2f0f8494a91934e9b86a35

There might still be issues on how this thing is being built. I have had trouble understanding the correct way to release npm modules. I guess I want a build as part of the release, not that the release command just wraps up what's currently in the local file system.

I see now that the releases aren't even tagged here in vcs so I guess I gotta look at that too.

**Comment by hedefalk** [comment]
Oh, I had just failed to push --tags.

**Comment by tomverran** [comment]
Hi, sorry I never updated you - I set up a local node repository and tested publishing your more recent branch and it all built correctly and uploaded only the compiled assets.

I then tried starting a clean project with only ensime-node as a dependency and the only issue was that fs-extra was required but not a dependency. Assuming that is fixed now the publishing process seems fine :+1:

**Comment by hedefalk** [comment]
Great, I'll close! 👍 

I've been making some progress and will try using it from vscode now. If you're into typescript maybe you can help answer my question here: http://stackoverflow.com/questions/39131347/why-does-tsc-give-so-cryptic-errors-when-leaking-transitive-implementation-types

Basically, I returned bluebird.Promise from ensime-node, which then fails in ensime-vcode since it hadn't any typings for it…
